export TOKEN_STORE_DIR="/Users/nilsontinassiperes/Development/OlistERPMediator/OlistERPMediator/auth/cmd"
export TSTORE_DB_NAME="postgres"
export TSTORE_DB_HOST="localhost"
export TSTORE_DB_USER="postgres"
export TSTORE_DB_PASSWORD="postgres"
export API_BASE_URL="http://localhost:8081"
export API_OLIST_URL="https://api.tiny.com.br/public-api/v3"
export ENCRYPTION_KEY="9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"